"""add generic tools support

Revision ID: d92e0c8e81e8
Revises: 50677d9fd8fd
Create Date: 2026-03-06 20:56:04.118723

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d92e0c8e81e8"
down_revision: str | Sequence[str] | None = "50677d9fd8fd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mcp_servers", sa.Column("tools_config", sa.JSON(), nullable=True))
    op.alter_column("mcp_servers", "datasource_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("mcp_servers", "datasource_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("mcp_servers", "tools_config")
    # ### end Alembic commands ###
